# 딥러닝 프로젝트
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Arsenal FC 팀, 개인 성적 데이터 분석
email: q64306940@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
필자는 평소 스포츠에 관심이 많으며 여러 종목에 해박한 편이다. 
그 중에서도 해외축구를 즐겨보고, 여러 구단 중 잉글랜드 프리미어리그에 속해있는 아스날FC의 Big Fan이다. 
4스날이라 불리며 신기할 정도로 항상 4위는 하던 팀이 최근 5년간 성적이 좋지 못했다.
그러한 팀의 성적을 분석해보면 흥미로운 결과를 얻을 수 있지 않을까 하여 이 프로젝트르 진행하고자 한다. 
최근 20년간 팀 성적 및 최근 3~5년간의 개인 성적 분석을 통해 올해 및 내년 시즌 성적 예측해 볼 것이다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DestiN_HS
github_username:  destinlee3

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
